baseURL = 'https://ahmedabouelkher.me'
languageCode = 'en-us'
title = 'Ahmed Abouelkher Blog'
theme = "lekh"

[params]
Name = "Ahmed Mahmoud"
About = "I'm an Electrical Engineering Student who loves coding, problem-solving and creating software that helps people. "
Email = "ahmedabouelkher1@gmail.com"
Resume = "" # Add the filename with file extension.
PostLimit = 10 # Sets the number of posts to display on the front page
GoatCounterCode = "https://ahmedabouelkher.goatcounter.com/count"

[[params.profiles]]
name = "GitHub"
url = "https://github.com/AhmedAbouelkher"

[[params.profiles]]
name = "Twitter"
url = "https://twitter.com/ahmedmabouelkhr"

[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/ahmed-m-abouelkher-609b951a5/"